"""Inspect the processed terminology knowledge base.

This script helps validate the output generated by scripts/build_kb.py before
building the deterministic matcher. It prints global statistics and allows
simple searches over aliases, concepts, products, and brands.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from textwrap import shorten
from typing import Any

from heliot_terms.normalization.text_normalizer import TextNormalizer


def main() -> None:
    parser = argparse.ArgumentParser(description="Inspect processed HELIOT terminology KB.")
    parser.add_argument(
        "--processed-dir",
        default="data/processed",
        help="Directory containing processed KB files.",
    )
    parser.add_argument(
        "--search",
        default=None,
        help="Search normalized aliases, concepts, products, and brands.",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=15,
        help="Number of examples to print for each section.",
    )

    args = parser.parse_args()
    processed_dir = Path(args.processed_dir)

    concepts = _read_jsonl(processed_dir / "concepts.jsonl")
    aliases = _read_jsonl(processed_dir / "aliases.jsonl")
    products = _read_jsonl(processed_dir / "drug_products.jsonl")
    brands = _read_jsonl(processed_dir / "drug_brands.jsonl")
    report = _read_json(processed_dir / "build_report.json")

    if args.search:
        _search_kb(
            query=args.search,
            concepts=concepts,
            aliases=aliases,
            products=products,
            brands=brands,
            top=args.top,
        )
        return

    _print_global_summary(concepts, aliases, products, brands, report)
    _print_alias_summary(aliases, top=args.top)
    _print_brand_summary(brands, top=args.top)
    _print_missing_concepts_from_report(report, top=args.top)


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    """Read a JSONL file into a list of dictionaries."""
    if not path.exists():
        raise FileNotFoundError(f"Missing processed file: {path}")

    records: list[dict[str, Any]] = []

    with path.open("r", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            line = line.strip()
            if not line:
                continue

            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at {path}:{line_number}") from exc

    return records


def _read_json(path: Path) -> dict[str, Any]:
    """Read a JSON file into a dictionary."""
    if not path.exists():
        raise FileNotFoundError(f"Missing processed file: {path}")

    with path.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object in {path}")

    return data


def _print_global_summary(
    concepts: list[dict[str, Any]],
    aliases: list[dict[str, Any]],
    products: list[dict[str, Any]],
    brands: list[dict[str, Any]],
    report: dict[str, Any],
) -> None:
    """Print global KB statistics."""
    _section("Global summary")

    print(f"Concepts:       {len(concepts):>8}")
    print(f"Aliases:        {len(aliases):>8}")
    print(f"Drug products:  {len(products):>8}")
    print(f"Drug brands:    {len(brands):>8}")

    print("\nReport counters:")
    for key, value in report.items():
        if key == "issues":
            continue
        print(f"- {key}: {value}")

    entity_counts = Counter(concept.get("entity_type", "unknown") for concept in concepts)
    print("\nConcept entity types:")
    for entity_type, count in entity_counts.most_common():
        print(f"- {entity_type}: {count}")


def _print_alias_summary(aliases: list[dict[str, Any]], top: int) -> None:
    """Print alias quality and safety statistics."""
    _section("Alias summary")

    category_counts = Counter(alias.get("alias_category", "unknown") for alias in aliases)
    target_type_counts = Counter(alias.get("target_type", "unknown") for alias in aliases)
    policy_reason_counts = Counter(
        alias.get("metadata", {}).get("policy_reason", "unknown") for alias in aliases
    )

    safe_count = sum(1 for alias in aliases if alias.get("safe_for_exact_match") is True)
    unsafe_count = len(aliases) - safe_count

    print(f"Safe for exact match:   {safe_count}")
    print(f"Excluded from exact:    {unsafe_count}")

    print("\nAlias categories:")
    for category, count in category_counts.most_common():
        print(f"- {category}: {count}")

    print("\nTarget types:")
    for target_type, count in target_type_counts.most_common():
        print(f"- {target_type}: {count}")

    print("\nPolicy reasons:")
    for reason, count in policy_reason_counts.most_common():
        print(f"- {reason}: {count}")

    ambiguous_aliases = [
        alias for alias in aliases if "ambiguous_targets" in alias.get("metadata", {})
    ]

    print(f"\nAmbiguous aliases: {len(ambiguous_aliases)}")
    for alias in ambiguous_aliases[:top]:
        print(
            f"- {alias['alias_raw']} -> {alias['metadata']['ambiguous_targets']}"
        )

    technical_aliases = [
        alias for alias in aliases if alias.get("alias_category") == "technical"
    ]
    technical_aliases = sorted(
        technical_aliases,
        key=lambda item: len(item.get("alias_raw", "")),
        reverse=True,
    )

    print(f"\nLongest technical aliases: {len(technical_aliases)}")
    for alias in technical_aliases[:top]:
        print(
            f"- {shorten(alias['alias_raw'], width=120)} "
            f"-> {alias['target_id']}"
        )


def _print_brand_summary(brands: list[dict[str, Any]], top: int) -> None:
    """Print drug brand aggregation statistics."""
    _section("Drug brand summary")

    status_counts = Counter(brand.get("brand_status", "unknown") for brand in brands)
    print("Brand statuses:")
    for status, count in status_counts.most_common():
        print(f"- {status}: {count}")

    ambiguous_brands = [
        brand for brand in brands if brand.get("brand_status") == "ambiguous_brand"
    ]

    print(f"\nAmbiguous brands: {len(ambiguous_brands)}")
    for brand in ambiguous_brands[:top]:
        signatures = brand.get("active_ingredient_signatures", [])
        print(f"- {brand['brand_name']} | signatures={signatures}")

    largest_brands = sorted(
        brands,
        key=lambda item: len(item.get("product_ids", [])),
        reverse=True,
    )

    print("\nBrands with most products:")
    for brand in largest_brands[:top]:
        print(
            f"- {brand['brand_name']} "
            f"({len(brand.get('product_ids', []))} products) "
            f"[{brand.get('brand_status')}]"
        )


def _print_missing_concepts_from_report(report: dict[str, Any], top: int) -> None:
    """Print examples of concepts created from drugs.csv because absent from JSON."""
    _section("Concepts created from drugs.csv")

    issues = report.get("issues", [])
    created_issues = [
        issue
        for issue in issues
        if issue.get("code", "").startswith("created_missing_")
    ]

    print(f"Total created from drugs.csv: {len(created_issues)}")

    for issue in created_issues[:top]:
        metadata = issue.get("metadata", {})
        print(
            f"- {issue.get('item_id')} | "
            f"raw_name={metadata.get('raw_name')} | "
            f"drug_code={metadata.get('drug_code')}"
        )


def _search_kb(
    query: str,
    concepts: list[dict[str, Any]],
    aliases: list[dict[str, Any]],
    products: list[dict[str, Any]],
    brands: list[dict[str, Any]],
    top: int,
) -> None:
    """Search the KB using a normalized query."""
    normalizer = TextNormalizer()
    query_normalized = normalizer.normalize(query)

    _section(f"Search: {query!r} -> {query_normalized!r}")

    alias_matches = [
        alias
        for alias in aliases
        if query_normalized in alias.get("alias_normalized", "")
        or query.lower() in alias.get("alias_raw", "").lower()
    ]

    concept_matches = [
        concept
        for concept in concepts
        if query_normalized in normalizer.normalize(concept.get("canonical_it", ""))
        or query_normalized in normalizer.normalize(concept.get("canonical_en", "") or "")
        or query_normalized in concept.get("concept_id", "")
    ]

    product_matches = [
        product
        for product in products
        if query_normalized in normalizer.normalize(product.get("drug_name", ""))
        or query_normalized in normalizer.normalize(product.get("brand_name", "") or "")
    ]

    brand_matches = [
        brand
        for brand in brands
        if query_normalized in brand.get("normalized_brand_name", "")
        or query.lower() in brand.get("brand_name", "").lower()
    ]

    print(f"Alias matches: {len(alias_matches)}")
    for alias in alias_matches[:top]:
        print(
            f"- {alias['alias_raw']} [{alias['alias_category']}] "
            f"safe={alias['safe_for_exact_match']} "
            f"-> {alias['target_id']} ({alias['target_type']})"
        )

    print(f"\nConcept matches: {len(concept_matches)}")
    for concept in concept_matches[:top]:
        print(
            f"- {concept['concept_id']} | "
            f"IT={concept.get('canonical_it')} | "
            f"EN={concept.get('canonical_en')}"
        )

    print(f"\nProduct matches: {len(product_matches)}")
    for product in product_matches[:top]:
        print(
            f"- {product['drug_name']} | "
            f"AIC={product['drug_code']} | "
            f"brand={product.get('brand_name')} | "
            f"active={product.get('active_ingredient_ids')}"
        )

    print(f"\nBrand matches: {len(brand_matches)}")
    for brand in brand_matches[:top]:
        print(
            f"- {brand['brand_name']} | "
            f"status={brand['brand_status']} | "
            f"active={brand.get('active_ingredient_ids')}"
        )


def _section(title: str) -> None:
    """Print a section title."""
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)


if __name__ == "__main__":
    main()